// Sample audio tracks for transition videos (Sound-to-Video clips)
const SAMPLE_AUDIO_CDN = 'https://cdn.sogni.ai/audio-samples';
const S2V_TRACKS = [
  { id: '6-feet', title: '6 Feet', emoji: '🎵', duration: '0:28' },
  { id: '8-ball', title: '8 Ball', emoji: '🎱', duration: '0:21' },
  { id: 'about-you', title: 'About You', emoji: '💕', duration: '1:17' },
  { id: 'all-eyes-on-me', title: 'All Eyes on Me', emoji: '👀', duration: '0:32' },
  { id: 'beez-in-the-trap', title: 'Beez in the Trap', emoji: '🐝', duration: '0:22' },
  { id: 'big-bad-john', title: 'Big Bad John', emoji: '💪', duration: '0:58' },
  { id: 'bless-the-telephone', title: 'Bless the Telephone', emoji: '☎️', duration: '1:08' },
  { id: 'brutus', title: 'Brutus', emoji: '🗡️', duration: '1:07' },
  { id: 'chan-chan', title: 'Chan Chan', emoji: '🎺', duration: '1:31' },
  { id: 'confidence-man-holiday', title: 'Confidence Man Holiday', emoji: '🌞', duration: '1:34' },
  { id: 'down-with-the-sickness', title: 'Down with the Sickness', emoji: '🤘', duration: '0:59' },
  { id: 'dtmf', title: 'DTMF', emoji: '📞', duration: '0:33' },
  { id: 'eclipse-philosophy', title: 'Eclipse Philosophy', emoji: '🌑', duration: '0:45' },
  { id: 'fast-as-f', title: 'Fast as F', emoji: '⚡', duration: '0:16' },
  { id: 'good-places', title: 'Good Places', emoji: '🌴', duration: '0:59' },
  { id: 'grandpa-on-retro', title: 'Grandpa on Retro', emoji: '🎸', duration: '0:35' },
  { id: 'hank-hill-hotdog', title: 'Hank Hill Hotdog', emoji: '🌭', duration: '0:42' },
  { id: 'have-you-ever-had-a-dream', title: 'Have You Ever Had a Dream', emoji: '💭', duration: '0:19' },
  { id: 'hitchhiker-11', title: 'Hitchhiker 11', emoji: '👽', duration: '1:02' },
  { id: 'hoist-the-colors', title: 'Hoist the Colors', emoji: '🏴‍☠️', duration: '0:29' },
  { id: 'hurricane-katrina', title: 'Hurricane Katrina', emoji: '🌀', duration: '0:24' },
  { id: 'im-a-snake', title: "I'm a Snake", emoji: '🐍', duration: '1:03' },
  { id: 'jet-2-holiday-jingle', title: 'Jet 2 Holiday Jingle', emoji: '✈️', duration: '0:13' },
  { id: 'kill-jill', title: 'Kill Jill', emoji: '🔥', duration: '0:28' },
  { id: 'kitty-bed', title: 'Kitty Bed', emoji: '🐱', duration: '0:18' },
  { id: 'listen-to-me-now', title: 'Listen to Me Now', emoji: '👂', duration: '0:10' },
  { id: 'look-at-that-cat', title: 'Look at That Cat', emoji: '🐱', duration: '0:45' },
  { id: 'louis-theroux-jiggle-giggle', title: 'Louis Theroux Jiggle Giggle', emoji: '🕺', duration: '0:22' },
  { id: 'mic-check', title: 'Mic Check', emoji: '🎤', duration: '1:01' },
  { id: 'mii-theme-trap-remix', title: 'Mii Theme Trap Remix', emoji: '🎮', duration: '0:31' },
  { id: 'n-95', title: 'N-95', emoji: '😷', duration: '0:17' },
  { id: 'noone-is-going-to-know', title: 'No One is Going to Know', emoji: '🤫', duration: '0:24' },
  { id: 'o-fortuna', title: 'O Fortuna', emoji: '🎭', duration: '0:31' },
  { id: 'once-in-a-lifetime', title: 'Once in a Lifetime', emoji: '🌊', duration: '0:41' },
  { id: 'panda', title: 'Panda', emoji: '🐼', duration: '0:44' },
  { id: 'peter-axel-f', title: 'Peter Axel F', emoji: '🎹', duration: '0:09' },
  { id: 'peter-pan', title: 'Peter Pan', emoji: '🧚', duration: '0:51' },
  { id: 'pimp', title: 'Pimp', emoji: '🎩', duration: '1:35' },
  { id: 'priceless', title: 'Priceless', emoji: '💎', duration: '0:14' },
  { id: 'runnin-through-the-6', title: 'Runnin Through the 6', emoji: '🏃', duration: '0:16' },
  { id: 'runnin-up-that-hill', title: 'Runnin Up That Hill', emoji: '⛰️', duration: '1:10' },
  { id: 'slice-of-heaven', title: 'Slice of Heaven', emoji: '☀️', duration: '0:48' },
  { id: 'spider-man-2099', title: 'Spider-Man 2099', emoji: '🕷️', duration: '0:29' },
  { id: 'suff-gucci', title: 'Suff Gucci', emoji: '💰', duration: '0:23' },
  { id: 'surround-sound', title: 'Surround Sound', emoji: '🔊', duration: '0:24' },
  { id: 'terrorize-my-heart', title: 'Terrorize My Heart', emoji: '💔', duration: '1:06' },
  { id: 'thats-all-right', title: "That's All Right", emoji: '👍', duration: '0:48' },
  { id: 'tokyo-drift', title: 'Tokyo Drift', emoji: '🏎️', duration: '0:42' },
  { id: 'trouble', title: 'Trouble', emoji: '😈', duration: '0:45' },
  { id: 'turn-it-down-for-what', title: 'Turn It Down for What', emoji: '🔊', duration: '0:39' },
  { id: 'welcome-to-derry', title: 'Welcome to Derry', emoji: '🎈', duration: '1:05' },
  { id: 'when-i-was-done-dying', title: 'When I Was Done Dying', emoji: '🌀', duration: '1:58' },
  { id: 'who-put-the-bomb', title: 'Who Put the Bomb', emoji: '💣', duration: '0:48' },
  { id: 'ylvis-the-fox', title: 'Ylvis The Fox', emoji: '🦊', duration: '0:32' }
];

// Preset music tracks for transition videos
export const TRANSITION_MUSIC_PRESETS = S2V_TRACKS.map(track => ({
  id: track.id,
  url: `${SAMPLE_AUDIO_CDN}/${track.id}.m4a`,
  title: track.title,
  emoji: track.emoji,
  duration: track.duration
}));
